apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekit-io
  namespace: default
  labels:
    app: tekit-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekit-io
  template:
    metadata:
      labels:
        app: tekit-io
    spec:
      containers:
      - name: tekit-io
        image: registry.tekit.io/tekit-io:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tekit-io
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: tekit-io
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tekit-io-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - tekit.io
    secretName: tekit-io-tls
  rules:
  - host: tekit.io
    http:
      paths:
      - backend:
          serviceName: tekit-io
          servicePort: 80